Repository SystemConsultantGroup/S-top-backend, pull requests merged in 2024-10, with the labels that each got.

#104 [FIX] 퀴즈 생성 및 응답 형식을 Json에서 List로 변경
  src/main/java/com/scg/stop/video/dto/request/QuizRequest.java
  src/main/java/com/scg/stop/video/dto/response/QuizResponse.java
  src/main/resources/static/docs/talk.html
  src/test/java/com/scg/stop/video/controller/TalkControllerTest.java
Labels: 🐞 Bug, 🎯 API, Vido Domain

#107 [FIX] Project 도메인 및 API 일부 수정
  src/main/java/com/scg/stop/project/domain/Project.java
  src/main/java/com/scg/stop/project/dto/request/ProjectRequest.java
  src/main/java/com/scg/stop/project/dto/response/ProjectDetailResponse.java
  src/main/java/com/scg/stop/project/dto/response/ProjectResponse.java
  src/main/resources/static/docs/aiHub-controller-test.html
  src/main/resources/static/docs/application.html
  src/main/resources/static/docs/auth-controller-test.html
  src/main/resources/static/docs/eventNotice.html
  src/main/resources/static/docs/eventPeriod.html
  src/main/resources/static/docs/exceptionCode.html
  src/main/resources/static/docs/file-controller-test.html
  src/main/resources/static/docs/gallery.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/inquiry.html
  src/main/resources/static/docs/jobInfo-controller-test.html
  src/main/resources/static/docs/jobInterview.html
  src/main/resources/static/docs/notice.html
  src/main/resources/static/docs/project.html
  src/main/resources/static/docs/quiz.html
  src/main/resources/static/docs/talk.html
  src/main/resources/static/docs/user-controller-test.html
  src/test/java/com/scg/stop/project/controller/ProjectControllerTest.java
Labels: 🐞 Bug, Project Domain

#109 [FIX] Quiz 및 Excel 관련 API 충돌 해결
  src/main/resources/static/docs/aiHub-controller-test.html
  src/main/resources/static/docs/application.html
Labels: 🐞 Bug, 🎯 API, Vido Domain

#108 [FEAT] 엑셀 다운로드 유틸 및 제출한 퀴즈 결과 엑셀로 받는 기능 구현 (#71)
  build.gradle
  src/docs/asciidoc/quiz.adoc
  src/main/java/com/scg/stop/global/excel/Excel.java
  src/main/java/com/scg/stop/global/excel/ExcelUtil.java
  src/main/java/com/scg/stop/global/excel/annotation/ExcelColumn.java
  src/main/java/com/scg/stop/global/excel/annotation/ExcelDownload.java
  src/main/java/com/scg/stop/global/exception/ExceptionCode.java
  src/main/java/com/scg/stop/video/controller/QuizController.java
  src/main/java/com/scg/stop/video/dto/response/UserQuizResultExcelResponse.java
  src/main/java/com/scg/stop/video/dto/response/UserQuizResultResponse.java
  src/main/java/com/scg/stop/video/repository/UserQuizRepository.java
  src/main/java/com/scg/stop/video/service/QuizService.java
  src/main/resources/static/docs/aiHub-controller-test.html
  src/main/resources/static/docs/application.html
  src/main/resources/static/docs/auth-controller-test.html
  src/main/resources/static/docs/eventNotice.html
  src/main/resources/static/docs/eventPeriod.html
  src/main/resources/static/docs/file-controller-test.html
  src/main/resources/static/docs/gallery.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/jobInfo-controller-test.html
  src/main/resources/static/docs/jobInterview.html
  src/main/resources/static/docs/notice.html
  src/main/resources/static/docs/project.html
  src/main/resources/static/docs/quiz.html
  src/main/resources/static/docs/talk.html
  src/test/java/com/scg/stop/video/controller/QuizControllerTest.java
Labels: 🚀 Feature, 🎯 API, Vido Domain

#110 [FEAT] Inquiry API 구현
  .github/workflows/CI.yml
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/inquiry.adoc
  src/main/java/com/scg/stop/global/config/AsyncConfig.java
  src/main/java/com/scg/stop/global/config/EmailServiceConfig.java
  src/main/java/com/scg/stop/global/config/MailConfig.java
  src/main/java/com/scg/stop/global/domain/EmailEvent.java
  src/main/java/com/scg/stop/global/eventListener/EmailEventListener.java
  src/main/java/com/scg/stop/global/exception/ExceptionCode.java
  src/main/java/com/scg/stop/global/infrastructure/EmailService.java
  src/main/java/com/scg/stop/global/infrastructure/TransactionalEmailService.java
  src/main/java/com/scg/stop/project/controller/InquiryController.java
  src/main/java/com/scg/stop/project/controller/ProjectController.java
  src/main/java/com/scg/stop/project/domain/Inquiry.java
  src/main/java/com/scg/stop/project/domain/InquiryReply.java
  src/main/java/com/scg/stop/project/domain/InquiryResponse.java
  src/main/java/com/scg/stop/project/dto/request/InquiryReplyRequest.java
  src/main/java/com/scg/stop/project/dto/request/InquiryRequest.java
  src/main/java/com/scg/stop/project/dto/response/InquiryDetailResponse.java
  src/main/java/com/scg/stop/project/dto/response/InquiryReplyResponse.java
  src/main/java/com/scg/stop/project/dto/response/InquiryResponse.java
  src/main/java/com/scg/stop/project/repository/InquiryReplyRepository.java
  src/main/java/com/scg/stop/project/repository/InquiryRepository.java
  src/main/java/com/scg/stop/project/service/InquiryService.java
  src/main/java/com/scg/stop/project/service/ProjectService.java
  src/main/resources/application.yml
  src/main/resources/static/docs/aiHub-controller-test.html
  src/main/resources/static/docs/application.html
  src/main/resources/static/docs/auth-controller-test.html
  src/main/resources/static/docs/eventNotice.html
  src/main/resources/static/docs/eventPeriod.html
  src/main/resources/static/docs/file-controller-test.html
  src/main/resources/static/docs/gallery.html
  src/main/resources/static/docs/index.html
  src/main/resources/static/docs/jobInfo-controller-test.html
  src/main/resources/static/docs/jobInterview.html
  src/main/resources/static/docs/notice.html
  src/main/resources/static/docs/project.html
  src/main/resources/static/docs/quiz.html
  src/main/resources/static/docs/talk.html
  src/test/java/com/scg/stop/inquiry/controller/InquiryControllerTest.java
Labels: 🚀 Feature, 🎯 API, Inquiry Domain
