Repository SystemConsultantGroup/S-top-backend, pull requests merged in 2025-02, with the labels that each got.

#141 [FEAT] 갤러리 역순정렬 추가
  src/main/java/com/scg/stop/gallery/repository/GalleryRepository.java
Labels: 🚀 Feature, 🎯 API, Gallery Domain

#144 [FEAT] 대담영상/잡페어 인터뷰 영상 최신순 정렬
  src/main/java/com/scg/stop/video/repository/JobInterviewRepository.java
  src/main/java/com/scg/stop/video/repository/TalkRepository.java
Labels: 🚀 Feature, 🎯 API, Vido Domain

#143 [FIX] 프로젝트 북마크/좋아요 취소 시 삭제가 안되는 버그 수정
  src/main/java/com/scg/stop/project/service/ProjectService.java
Labels: 🐞 Bug, 🎯 API, Project Domain

#147 [FIX] application-common.yml 의 redirectUri를 prod용 도메인으로 수정
  .github/workflows/CD-prod.yml
  .github/workflows/CD-qa.yml
  .github/workflows/CI.yml
  src/main/resources/application-common.yml
Labels: 🐞 Bug, 🎯 API, auth domain

#149 [FIX] Multipart 최대 업로드 용량 변경
  src/main/resources/application-common.yml
Labels: 🐞 Bug, 🎯 API, File Domain

#150 [FIX] Duplicate key 오류 수정
  src/main/resources/application-common.yml
Labels: 🐞 Bug, 🎯 API, File Domain

#154 [FIX] 올해 프로젝트 조회시 순서 랜덤하게 응답
  src/main/java/com/scg/stop/project/repository/ProjectRepository.java
  src/main/java/com/scg/stop/project/service/ProjectService.java
Labels: 🚀 Feature
